### ISSUE TITLE
Issue enabling save_after_reboot

### ISSUE THREAD

**Issue by itisgriff** [frafol/PlayerVisibility#1]
Hello I am currently getting this error after enabling save_after_reboot option being enabled.

```console[16:10:16] [Server thread/INFO]: [PlayerVisibility] Enabling PlayerVisibility v1.0.2
[16:10:16] [Server thread/INFO]: [PlayerVisibility] Loading dependencies...
[16:10:16] [Server thread/INFO]: [PlayerVisibility] Loading configuration...
[16:10:16] [Server thread/INFO]: [PlayerVisibility] Loading commands...
[16:10:16] [Server thread/INFO]: [PlayerVisibility] Loading listeners...
[16:10:16] [Server thread/INFO]: [PlayerVisibility] Loading database...
[16:10:16] [Server thread/ERROR]: Error occurred while enabling PlayerVisibility v1.0.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "it.frafol.playervisibility.enums.Data.get(java.lang.Class)" is null
	at it.frafol.playervisibility.PlayerVisibility.loadDatabase(PlayerVisibility.java:128) ~[PlayerVisibility.jar:?]
	at it.frafol.playervisibility.PlayerVisibility.onEnable(PlayerVisibility.java:46) ~[PlayerVisibility.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1148) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[16:10:16] [Server thread/INFO]: [PlayerVisibility] Disabling PlayerVisibility v1.0.2
[16:10:16] [Server thread/INFO]: [PlayerVisibility] Disabled successfully.
```

The data file default is ```hidden: false``` but changing it to ```hidden: true``` throws the error.

**Comment by frafol** [comment]
Hi, try removing the data file and have it regenerated, once regenerated don't change it, use the command in the server to hide the players and it will change to the file automatically

**Comment by itisgriff** [comment]
I have done that but as soon as I set ```save_after_reboot: true``` it throws this error in the console and the plugin does not load.
```console
[14:30:47] [Server thread/INFO]: [PlayerVisibility] Enabling PlayerVisibility v1.0.2
[14:30:47] [Server thread/INFO]: [PlayerVisibility] Loading dependencies...
[14:30:47] [Server thread/INFO]: [PlayerVisibility] Loading configuration...
[14:30:47] [Server thread/INFO]: [PlayerVisibility] Loading commands...
[14:30:47] [Server thread/INFO]: [PlayerVisibility] Loading listeners...
[14:30:47] [Server thread/INFO]: [PlayerVisibility] Loading database...
[14:30:47] [Server thread/ERROR]: Error occurred while enabling PlayerVisibility v1.0.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "it.frafol.playervisibility.enums.Data.get(java.lang.Class)" is null
	at it.frafol.playervisibility.PlayerVisibility.loadDatabase(PlayerVisibility.java:128) ~[PlayerVisibility.jar:?]
	at it.frafol.playervisibility.PlayerVisibility.onEnable(PlayerVisibility.java:46) ~[PlayerVisibility.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1148) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2120]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:30:47] [Server thread/INFO]: [PlayerVisibility] Disabling PlayerVisibility v1.0.2
[14:30:47] [Server thread/INFO]: [PlayerVisibility] Disabled successfully.

**Comment by itisgriff** [comment]
For context, this is a completely new generated folder of the plugin so the config.yml and data.yml generated themselves and are default. The only thing I changed was the ```save_after_reboot``` from false to true. As soon as I make that change I get the error above. Running latest PurPur 1.20.4 build.
